### ISSUE TITLE
count(*) causes an weired syntax error message

### ISSUE THREAD

**Issue by tatsuo-ishii** [sraoss/pgsql-ivm#23] opened 2019-09-21 21:33 UTC
```
 create incremental materialized view mv1 as select count(*),avg(abalance),min(abalance),max(abalance) from pgbench_accounts;
2019-09-22 06:25:09.264 JST [31280] ERROR:  syntax error at or near "base_type" at character 1
2019-09-22 06:25:09.264 JST [31280] STATEMENT:  base_type,
	    SFUNC = sfunc,
	
	create incremental materialized view mv1 as select count(*),avg(abalance),min(abalance),max(abalance) from pgbench_accounts;
ERROR:  syntax error at or near "base_type"
LINE 1: base_type,
        ^
```

**Comment by yugo-n** [comment] 2019-09-24 01:32
I can not reproduce this using the latest IVM branch code. Could you reconfirm this?

issue23=# create incremental materialized view mv1 as select count(*),avg(abalance),min(abalance),max(abalance) from pgbench_accounts;
SELECT 1

**Comment by yugo-n** [comment] 2019-09-25 01:26
The statements which appear in the log output seems related to CREATE AGGREGATE but these are not performed in our codes. One possibility is that our code accidentally refer some garbage remained in the memory due to regression test. Although this must not occur of course because string buffers should be initialized before used, I'll recheck my code carefully.

**Comment by yugo-n** [comment] 2020-04-15 02:27
@tatsuo-ishii We have not observe this phenomenon yet, so may we close this issue?  If this occurs again,  let's reopen this or open new one.

**Comment by yugo-n** [comment] 2020-12-08 04:19
We have not seen this problem for a long time, so I will close this. If we find this again, it will be reopened.

**Closed as completed by yugo-n** 2020-12-08 04:19 UTC
